python_binary(
    name = 'search_example',
    dependencies = [
        "src/python/algorithmics:search"
    ],
    source = 'search_example.py',
)

python_library(
    name = 'search',
    dependencies = [
    ],
    sources = ['search.py'],
)
