python_binary(
    name = 'hash_map_example',
    dependencies = [
        "src/python/algorithmics:hash_map",
    ],
    source = 'hash_map_example.py',
)

python_library(
    name = 'hash_map',
    dependencies = [
        '3rdparty/python:typing-extensions',
    ],
    sources = ['hash_map.py'],
)

python_binary(
    name = 'queue_example',
    dependencies = [
        "src/python/algorithmics:queue",
    ],
    source = 'queue_example.py',
)

python_library(
    name = 'queue',
    dependencies = [
        "src/python/algorithmics:stack",
    ],
    sources = ['queue.py'],
)

python_binary(
    name = 'search_example',
    dependencies = [
        "src/python/algorithmics:search",
    ],
    source = 'search_example.py',
)

python_library(
    name = 'search',
    dependencies = [
    ],
    sources = ['search.py'],
)

python_binary(
    name = 'stack_example',
    dependencies = [
        "src/python/algorithmics:stack",
    ],
    source = 'stack_example.py',
)

python_library(
    name = 'stack',
    dependencies = [
    ],
    sources = ['stack.py'],
)
