python_tests(
  dependencies = [
    'src/python/algorithmics:balanced_parentheses',
    'src/python/algorithmics:hash_map',
    'src/python/algorithmics:misc',
    'src/python/algorithmics:queue',
    'src/python/algorithmics:search',
    'src/python/algorithmics:stack',
  ],
)
